include: package:flutter_lints/flutter.yaml

analyzer:
    exclude:
        - lib/**.g.dart
        - lib/generated/intl/**.dart
        - lib/generated_plugin_registrant.dart
        - test/**.mocks.dart

rules:
    lines_longer_than_80_chars: false
