// Mocks generated by Mockito 5.0.14 from annotations
// in film_freund/test/services/service_locator_test.dart.
// Do not manually edit this file.

import 'package:film_freund/services/service_locator.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ITestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITestService extends _i1.Mock implements _i2.ITestService {
  MockITestService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int myMethod() =>
      (super.noSuchMethod(Invocation.method(#myMethod, []), returnValue: 0)
          as int);
  @override
  String toString() => super.toString();
}
